
// TUI: Text User Interface
// (C) BlockHead aka Guru, 2001.

// Global header file

#include "textio.h"     // WriteXYC
#include "tuitypes.h"   // data types
#include "tuifiles.h"   // FileExist
#include "tuikeys.h"    // keycodes
#include "tuistr.h"     // Str*
#include "tuidate.h"    // DATE, DateToday
#include "tuistd.h"     // common classes
#include "tuiext.h"     // extended classes
#include "tuidlgs.h"    // dialogs
#include "tuimouse.h"   // mouse fns

#include "tuimacro.h"   // useful macros