
#ifndef _TUICONST_H
#define _TUICONST_H

// color names are in "textio.h"

// default color set
#define ccDesktop               0x03    // desktop
#define ccStatus                0x70    // status bar
#define ccStatusHi              0x74    // status bar highlight
#define ccDosWindow             0x07    // DOS color
#define ccShadow                0x07    // window shadow
#define ccDialog                0x70    // dialog window
#define ccDialogMove            0x72    // dialog window moving
#define ccStaticText            0x70    // static text
#define ccStaticTextHi          0x7E    // static text highlight
#define ccGroup                 0x30    // group
#define ccDivider               0x70    // divider
#define ccButton                0x20    // button normal
#define ccButtonHi              0x2E    // button normal highlight
#define ccButtonD               0x2B    // button default
#define ccButtonDHi             0x2E    // button default highlight
#define ccButtonA               0x2F    // button selected
#define ccButtonAHi             0x2E    // button selected highlight
#define ccButtonShadow          0x70    // button shadow
#define ccEdit                  0x1E    // edit line
#define ccEditA                 0x1F    // edit line focused
#define ccEditIcon              0x1A    // edit icons
#define ccEditIconA             0x1A    // edit icons focused
#define ccEditView              0x1B    // edit line (view mode)
#define ccEditViewIcon          0x1A    // edit icons (view mode)
#define ccEditDateIconE         0x1E    // edit date symbols (edit mode)
#define ccEditDateIconV         0x1E    // edit date symbols (view mode)
#define ccDateRect              0x30    // date box rect
#define ccDateWeek              0x31    // date box weekday titles
#define ccDateWeekEnd           0x34    // date box weekend titles
#define ccDateDays              0x30    // date box current month days
#define ccDateDaysX             0x37    // date box non-current month days
#define ccDateYear              0x3F    // date box year
#define ccDateMonth             0x3F    // date box month
#define ccDateCur               0x0A    // date box cursor
#define ccCheck                 0x30    // check box
#define ccCheckHi               0x3E    // check box highlight
#define ccCheckA                0x3F    // check box selected
#define ccCheckAHi              0x3E    // check box selected highlight
#define ccList                  0x30    // list box
#define ccListDiv               0x30    // list box divider
#define ccListA                 0x03    // list box: focused item
#define ccListS                 0x31    // list box: selected item
#define ccCustomList            0x70    // custom list
#define ccCustomListA           0x0F    // custom list: focused item (cursor)
#define ccCustomListS           0x71    // custom list: selected item
#define ccCustomListTitle       0x30    // custom list title bar
#define ccScroller              0x13    // scroll bar
#define ccScrollerIcon          0x13    // scroll bar icon
#define ccProgressWin           0x70    // progress window
#define ccProgressBar           0x07    // progress bar
#define ccProgressNum           0x7F    // progress percent
#define ccMenuListNorm          0x70    // menu list item
#define ccMenuListNormHi        0x7E    // menu list item highlight
#define ccMenuListFocus         0x0F    // menu list focused
#define ccMenuListFocusHi       0x0E    // menu list focused highlight
#define ccMenuListSel           0x0A    // menu list selected
#define ccMenuListSelHi         0x0B    // menu list selected highlight

// TUI colors
extern char cDesktop         ;        // desktop
extern char cStatus          ;        // status bar
extern char cStatusHi        ;        // status bar highlight
extern char cDosWindow       ;        // DOS color
extern char cShadow          ;        // window shadow
extern char cDialog          ;        // dialog window
extern char cDialogMove      ;        // dialog window moving
extern char cStaticText      ;        // static text
extern char cStaticTextHi    ;        // static text highlight
extern char cGroup           ;        // group
extern char cDivider         ;        // divider
extern char cButton          ;        // button normal
extern char cButtonHi        ;        // button normal highlight
extern char cButtonD         ;        // button default
extern char cButtonDHi       ;        // button default highlight
extern char cButtonA         ;        // button selected
extern char cButtonAHi       ;        // button selected highlight
extern char cButtonShadow    ;        // button shadow
extern char cEdit            ;        // edit line
extern char cEditA           ;        // edit line focused
extern char cEditIcon        ;        // edit icons
extern char cEditIconA       ;        // edit icons focused
extern char cEditView        ;        // edit line (view mode)
extern char cEditViewIcon    ;        // edit icons (view mode)
extern char cEditDateIconE   ;        // edit date symbols (edit mode)
extern char cEditDateIconV   ;        // edit date symbols (view mode)
extern char cDateRect        ;        // date box rect
extern char cDateWeek        ;        // date box weekday titles
extern char cDateWeekEnd     ;        // date box weekend titles
extern char cDateDays        ;        // date box current month days
extern char cDateDaysX       ;        // date box non-current month days
extern char cDateYear        ;        // date box year
extern char cDateMonth       ;        // date box month
extern char cDateCur         ;        // date box cursor
extern char cCheck           ;        // check box
extern char cCheckHi         ;        // check box highlight
extern char cCheckA          ;        // check box selected
extern char cCheckAHi        ;        // check box selected highlight
extern char cList            ;        // list box
extern char cListDiv         ;        // list box divider
extern char cListA           ;        // list box: focused item
extern char cListS           ;        // list box: selected item
extern char cCustomList      ;        // custom list
extern char cCustomListA     ;        // custom list: focused item (cursor)
extern char cCustomListS     ;        // custom list: selected item
extern char cCustomListTitle ;        // custom list title bar
extern char cScroller        ;        // scroll bar
extern char cScrollerIcon    ;        // scroll bar icon
extern char cProgressWin     ;        // progress window
extern char cProgressBar     ;        // progress bar
extern char cProgressNum     ;        // progress percent
extern char cMenuListNorm    ;        // menu list item
extern char cMenuListNormHi  ;        // menu list item highlight
extern char cMenuListFocus   ;        // menu list focused
extern char cMenuListFocusHi ;        // menu list focused highlight
extern char cMenuListSel     ;        // menu list selected
extern char cMenuListSelHi   ;        // menu list selected highlight

#endif







